### ISSUE TITLE
Unable to publish changes to minasearch.com

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-block-explorer#1017]
https://buildkite.com/granola/mina-block-explorer-tier-1/builds/2063#0192175d-6f4d-4f6b-a1b7-70ab20c57642

**Comment by jhult** [comment]
Fixed by https://github.com/Granola-Team/mina-block-explorer/commit/22c6d2721efd17710de1fb07171a96b4cbda71cb (as seen by [build 173](https://buildkite.com/granola/mina-block-explorer-tier-2/builds/173))
