### ISSUE TITLE
Sorting is not supported in tables, though the sort indicator is present

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-block-explorer#1030]

**Comment by jhult** [comment]
@n1tranquilla, can you provide an example or more details?

**Comment by jhult** [comment]
Example: https://minasearch.com/staking-ledgers

Clicking on `Total Staking %` doesn't work.

**Comment by n1tranquilla** [comment]
on ME
* "stake" and "delegator" are sortable: https://minaexplorer.com/staking
* almost all columns sortable for staker leaderboard: https://minaexplorer.com/top-epoch-stakers

If we're going to implement sorting on any tables, we can start with these.
