### ISSUE TITLE
Txn Status is showing as Failed when it is Applied

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-block-explorer#1041]
https://minasearch.com/blocks/3NLdMNamBNNP6gW3gupv7pbzhVq6Grpxu1RG7hvSBHSxkEb62r8m/commands/user

See block spotlight tab and user commands tab.

**Comment by Isaac-DeFrain** [comment]
Related to #1207

**Comment by n1tranquilla** [comment]
Updating local integrated indexer to `f96828a51d78f6ef436c96a65a7c20f54b9f55d2`. We will see if associated tests pass.
