### ISSUE TITLE
Cannot navigate "back" out of account spotlight

### ISSUE THREAD

**Issue by Isaac-DeFrain** [Granola-Team/mina-block-explorer#1079]
Once in a block spotlight, one cannot exit by going back.

**Comment by n1tranquilla** [comment]
Thanks for logging this, I had to recently fix a similar issue on another page.

**Comment by n1tranquilla** [comment]
I'm not able to reproduce this by visiting and back navigating. Could you give me your use case?

**Comment by Isaac-DeFrain** [comment]
Block spotlight back navigation is working now, but account spotlight back navigation is not.

**Comment by n1tranquilla** [comment]
Unable to reproduce
