### ISSUE TITLE
Display 0 fees differently

### ISSUE THREAD

**Issue by jhult** [Granola-Team/mina-block-explorer#1118]
Perhaps it would be better to show 0 fee amounts as one of the following:

- `Free`
- `None`
- `-`

**Comment by jhult** [comment]
@n1tranquilla, thoughts?

When displaying these amounts in table rows, if we allow sorting/filtering, this could affect that.

**Comment by n1tranquilla** [comment]
Yeah this seems fine to me. Are you thinking for the snarks tables?

**Comment by jhult** [comment]
I was thinking anywhere/everywhere.
