### ISSUE TITLE
Accounts: Account list page

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-block-explorer#145]
We need a page that helps us find accounts.

**Comment by n1tranquilla** [comment]
We don't have an endpoint that lists accounts

**Comment by trevorbernard** [comment]
@n1tranquilla [https://minaexplorer.com/all-accounts](https://minaexplorer.com/all-accounts)

But I can confirm there isn't an accounts API in the MinaExplorer GQL. I had a conversation with Gareth previous and it was error prone and untenable.

**Comment by n1tranquilla** [comment]
The all-accounts endpoint is error prone?

**Comment by n1tranquilla** [comment]
I remember the problem. These requests have an https://minaexplorer.com/ origin and calling them results in CORS errors. So this remains blocked
