### ISSUE TITLE
Problem: nanomina conversion to mina uses f64 which has the potential for representation errors

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-block-explorer#176]
Solution: Convert nanomina Strings to decimal and set the scale to `1_000_000_000u32`.

Also I would drop all trailing zeros after period..

E.g `1000` nanomina will be converted to `0.000001000` mina. We should display `0.000001`

**Comment by n1tranquilla** [comment]
@trevorbernard perhaps we can log this for when there is an actual bug. Unless you want to convert this issue into just a formatting task with only the following criteria:

> Also I would drop all trailing zeros after period..
E.g 1000 nanomina will be converted to 0.000001000 mina. We should display 0.000001

**Comment by trevorbernard** [comment]
> @trevorbernard perhaps we can log this for when there is an actual bug. Unless you want to convert this issue into just a formatting task with only the following criteria:

It is a bug. Unless you explicitly handle pips in floating point numbers there will always be representation errors because not all floats can be represented in base 2. Easiest to just used a fixed point decimal to represent Mina and u64 for nanomina.

**Comment by robinbb** [comment]
@n1tranquilla to rewrite this issue.
