### ISSUE TITLE
Problem: 'app' directory not deleted by 'just clean'

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-block-explorer#243]

**Comment by n1tranquilla** [comment]
By 'app' do you mean the 'dist' directory, where the build is output?

**Comment by trevorbernard** [comment]
@robinbb ^

**Comment by robinbb** [comment]
No, there is a directory called 'app' in my repo's root directory. Maybe that directory is no longer built?

**Comment by n1tranquilla** [comment]
There used to be a long time ago. Since we switched to Leptos, there is no longer such a directory.
