### ISSUE TITLE
Problem: transactions should be sorted by nonce descending  

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-block-explorer#363]
Sorting by block height isn't sufficient since transactions may come from the same block and there is no guarantee it will be displayed in the correct order.

**Comment by trevorbernard** [comment]
Here is an example: https://minasearch.com/addresses/accounts/B62qmPb2YVWP7vKXzpxgSNZRrRU8mrouzcLUG6v7EDNAVBbw7AiHodq

**Comment by trevorbernard** [comment]
Actually is this a problem? We want to maintain sorting by height and tie break based on NONCE_DESC. Can we even achieve this in GQL?

**Comment by n1tranquilla** [comment]
I'm not sure we can perform a compound sort on both BLOCKHEIGHT_DESC and NONCE on the server side.

**Comment by robinbb** [comment]
No achievable with GQL. Closing.
