### ISSUE TITLE
CI tests fail at the beginning of a new epoch for `next stakes` page

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-block-explorer#378]

**Comment by jhult** [comment]
Makes sense due to the next staking ledger only being available after 290 blocks of the epoch.

**Comment by robinbb** [comment]
@n1tranquilla Is this still an issue?

**Comment by n1tranquilla** [comment]
It is. I still can't think of a good work around. We don't know when the 290 blocks of the next epoch are complete, as the summary endpoint only exposes slots. 

If we exposed the number of blocks per epoch, we could accomplish this by filtering out tests - not a great idea. 

Something feels fundamentally broken about this "next stakes" page. There should not be no unfiltered tabular views that sometimes have no data in them.

**Comment by robinbb** [comment]
@n1tranquilla Does this happen because the "next stakes" are not available for the first *k* (290) blocks of the epoch? Or, are they available, but we choose not to display them until *k + 1*?

**Comment by robinbb** [comment]
@n1tranquilla Let's up-prioritize the failing CI tests. Pinging you about this one.

**Comment by n1tranquilla** [comment]
We no longer have a dedicated next stakes page, so this is a non issue.
