### ISSUE TITLE
Enhancement: Allow searching/filtering on ZK app transactions

### ISSUE THREAD

**Issue by jhult** [Granola-Team/mina-block-explorer#416]
https://minasearch.com/transactions/zk-txn

<img width="1105" alt="image" src="https://github.com/Granola-Team/mina-block-explorer/assets/9849069/3d46b693-1e1e-4e5e-8f91-a0042e9979d7">

**Comment by n1tranquilla** [comment]
This page is stubbed for now.

**Comment by n1tranquilla** [comment]
Closing, as this page is stubbed and hidden behind feature flag right now. It will go through another round of development, at which time we will develop all the features.
