### ISSUE TITLE
Bug: Searching/filtering does not work for any addresses pages

### ISSUE THREAD

**Issue by jhult** [Granola-Team/mina-block-explorer#418]
https://minasearch.com/addresses

[filtering.webm](https://github.com/Granola-Team/mina-block-explorer/assets/9849069/2b5cd1b2-32b4-4ce0-90bc-17a9e2ab5b88)

**Comment by n1tranquilla** [comment]
This page is stubbed for now. The data is fake.

**Comment by n1tranquilla** [comment]
Closing, as this is intentionally a non-functioning page.
