### ISSUE TITLE
Enhancement: Better column spacing

### ISSUE THREAD

**Issue by jhult** [Granola-Team/mina-block-explorer#419]
Some examples are below:

### Example 1

URL: https://minasearch.com/addresses/accounts
Notice: _Username_, _Balance_, _Nonce_ are too big
![image](https://github.com/Granola-Team/mina-block-explorer/assets/9849069/d6271d07-1a2e-4e33-a5ba-a1c66f7a7983)

### Example 2
URL: https://minasearch.com
Notice: _Coinbase Receiver_ has no padding on right side; _Coinbase_ and _Transactions_ too big
![image](https://github.com/Granola-Team/mina-block-explorer/assets/9849069/874742ec-afe2-4289-ae1f-ef093446b39d)

### Example 3
URL: https://minasearch.com/transactions
Notice: _Age_, _Transactions_ are too big
![image](https://github.com/Granola-Team/mina-block-explorer/assets/9849069/1ac105b4-9388-4ea2-805e-0f4891fc2592)
![image](https://github.com/Granola-Team/mina-block-explorer/assets/9849069/860d2a61-5abd-49a0-871f-67b296c59f0e)

### Example 4
URL: https://minasearch.com/transactions
Notice: Zoomed out to 80% and it looks pretty good (so this may prove tricky to fix on many different screen resolutions
![image](https://github.com/Granola-Team/mina-block-explorer/assets/9849069/9bcec659-5fc0-46d8-96be-0585c55d46a8)

### Example 5
URL: https://minasearch.com/addresses/accounts
Notice: _Username_, _Balance_, _Time Locked_ are too big
![image](https://github.com/Granola-Team/mina-block-explorer/assets/9849069/47ac3ba8-0bb5-4734-a394-4e7406bcf0b7)
![image](https://github.com/Granola-Team/mina-block-explorer/assets/9849069/41fe5b97-526b-4635-b498-22757543b3f5)

**Comment by n1tranquilla** [comment]
Can you upload your screen resolution? The tables look different depending upon the resolution.

**Comment by jhult** [comment]
14-inch Liquid Retina XDR Display (3024 × 1964)
