### ISSUE TITLE
Continuous Delivery is not occurring for mina-block-explorer

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-block-explorer#44]
Goal is to continually deploy code changes to staging and production environments

**Comment by trevorbernard** [comment]
There are security implications on allowing forks to automatically trigger builds from untrusted 3rd parties. We must discuss and decide on a direction at a later time.

**Comment by jhult** [comment]
[GitGuardian](https://www.gitguardian.com/) has some [security best practices (around GitHub Actions)](https://blog.gitguardian.com/github-actions-security-cheat-sheet/) that may provide some helpful insights.

**Comment by jhult** [comment]
Related Indexer issue: https://github.com/Granola-Team/mina-indexer/issues/212

**Comment by robinbb** [comment]
@jhult Let me know what you need to automate this, please, @jhult. I would like to up-prioritize.

**Comment by jhult** [comment]
I just sent a request.

<img width="509" alt="image" src="https://github.com/Granola-Team/mina-block-explorer/assets/9849069/90f15568-0367-4304-af09-ba0256336819">

@robinbb, I believe there is something for you to review [here](https://github.com/organizations/Granola-Team/settings/installations).

**Comment by n1tranquilla** [comment]
We're still deploying a preview instance: https://buildkite.com/granola/mina-block-explorer/builds/1390#018fc08c-11d4-4725-8a15-12a612abd49f
