### ISSUE TITLE
Problem: Cannot navigate directly to a known staking ledger

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-block-explorer#497]
One cannot go directly to staking ledger for epoch 42, for example. There is only a "previous"/"next" button set (https://minasearch.com/stakes).

**Comment by n1tranquilla** [comment]
What is the preferred way to navigate to an epoch? By hash or by number?

**Comment by robinbb** [comment]
I think by number. Could use an "E" prefix as shorthand, too; that would allow "multi-search" bar to search by epoch. (Unaddorned numbers are block height.)

**Comment by n1tranquilla** [comment]
I've been thinking about this problem.  I think the new global search bar that we have envisioned in [this ticket](https://github.com/Granola-Team/mina-block-explorer/issues/532) will solve this problem. I imagine we have a ledger hash, and we paste it into the global search bar and hit enter, and we're taken to the appropriate staking page.

**Comment by n1tranquilla** [comment]
For now, we are able to type in a number into the global search bar and hit enter and be taken to the staking ledger for that epoch number. For now, that seems the best interpretation for any number entered into the global search bar (other numbers such as block height may not have exactly one result). 

But as mentioned before, a better way to implement navigation to a staking ledger is by having the ledger hash. That is still coming, even though this ticket can now be closed.
