### ISSUE TITLE
Cannot sort Staking Ledgers by top delegates (block producers)

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-block-explorer#500]
Sorting to find the top staking delegates is important, so it makes sense to allow sorting them. Alternately, the staking ledgers page could always present the tabular data sorted by top delegates (by stake).

**Comment by robinbb** [comment]
I think that we can't move the milestone on this one, as this is clearly a feature of ME, despite the fact that ME does not expose an API that allows us to get at the information.

**Comment by Isaac-DeFrain** [comment]
We could include an index for this in the db like we have for [top snarker producers](https://github.com/Granola-Team/mina-indexer/pull/794)

**Comment by robinbb** [comment]
@Isaac-DeFrain Yup, we'll have to implement the feature in mina-indexer, indeed.

**Comment by Isaac-DeFrain** [comment]
I can take this one

**Comment by n1tranquilla** [comment]
I think this issue is not on the critical path to equivalence, unless we can point to a feature that ME has that this supports

**Comment by robinbb** [comment]
"Sorting to find the top staking delegates is important, so it makes sense to allow sorting them. Alternately, the staking ledgers page could always present the tabular data sorted by top delegates (by stake)." This was the original requirement for this issue. It was in the "next" column because Isaac has already started on the work, judging by the status of this issue yesterday.

https://minaexplorer.com/top-epoch-stakers - ME has this.

**Comment by n1tranquilla** [comment]
Blocked on https://github.com/Granola-Team/mina-indexer/issues/979 and #704

**Comment by n1tranquilla** [comment]
This _may_ be closes by #501 since with the addition of stake weight, and the change to the default sort.

**Comment by n1tranquilla** [comment]
@robinbb I want to see if you think this page now satisfies this ticket: https://minasearch.com/staking-ledgers?epoch=0

**Comment by n1tranquilla** [comment]
With the addition of filtering by balance_lte, I think we could scan the entire ledger (since the default sorting is now stake_desc)

**Comment by robinbb** [comment]
@n1tranquilla I think it does. However (and this need not necessarily be done as part of this ticket), despite the fact that the page *seems* sorted by stake%, it may not be clear to the user that it is. Or, the user may not be certain, and may wonder if larger stake percentages are simply not being shown (they are beyond the 100th entry, and the page only shows 100 entries). How about some sort of arrow next to the column to indicate that it really is sorted by that column?

**Comment by robinbb** [comment]
@n1tranquilla Regardless, this issue is no blocked, is it?

**Comment by n1tranquilla** [comment]
It is no longer blocked
