### ISSUE TITLE
Staking ledger is not displaying total stake weight

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-block-explorer#501]
The percentage of total stake should be a column on the staking ledger page. Or, there shoud be another page that adds this useful stat to the data displayed on the staking ledger page. (The latter idea allows the staking ledger page to be a pure presentation of what's in the ledger.)

**Comment by n1tranquilla** [comment]
Same issue as https://github.com/Granola-Team/mina-block-explorer/issues/502. We this data is not exposed and would need to be stored in a precomputed view. I don't think we can simply combine total supply from the api.minaexplorer.com endpoint with the stake of each address to get stake percentage for the current epoch. Even if that is the correct calculation, it would only work for the current epoch. I think we need to move this to `maintenance`

**Comment by robinbb** [comment]
We need to have evidence of this feature in the front-end to be considered equivalent to ME, despite the fact that ME does not allow us to get this information via API.

**Comment by trevorbernard** [comment]
This is the blocker: 
https://github.com/Granola-Team/mina-indexer/issues/874

**Comment by n1tranquilla** [comment]
Blocked on #714
