### ISSUE TITLE
Missing `block production %age` column in the staking ledger page

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-block-explorer#502]
The staking ledger should include a column called something like "block win percentage" that shows how often a given delegate wins. This could be on the staking ledger page, or on a new page that adds such a column.

We choose "Block Production Percentage" to indicate the fraction of blocks produced by the applicable public key in the epoch.

**Comment by n1tranquilla** [comment]
Unfortunately this data is not exposed at all by the graphql endpoint. We would have to create view. Does this change the milestone to `maintenance`?

**Comment by robinbb** [comment]
We need evidence of this feature in the front-end for the front-end to be considered ME-equivalent, alas. So, despite the fact that ME does not expose this data via its API, we must have front-end evidence of the feature.

**Comment by n1tranquilla** [comment]
Front end work has been done on this PR but it remains blocked due to lacking staking ledger data in the production indexer

**Comment by robinbb** [comment]
Blocked by Granola-Team/mina-indexer#979

**Comment by n1tranquilla** [comment]
Can be accomplished within the equivalence milestone

**Comment by robinbb** [comment]
Milestones are a "must". If this need not be accomplished within the Equivalence milestone, then it should not be in that milestone. While grooming, we decided this was "Maintenance", no?
