### ISSUE TITLE
Problem: staking ledger is missing the "name" of the block producer or delegate

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-block-explorer#504]

**Comment by robinbb** [comment]
I agree that ME does not provide this via API, but alas I do not believe that this can be moved to Maintenance. We're going to have to show evidence of support for "name" in the front-end in order to have ME equivalance, IMO.

**Comment by robinbb** [comment]
Blocked by Granola-Team/mina-indexer#896

**Comment by Isaac-DeFrain** [comment]
Unblocked by Granola-Team/mina-indexer#993

**Comment by n1tranquilla** [comment]
Blocked on #501
