### ISSUE TITLE
Unable to easily see all of stake delegations

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-block-explorer#507]

**Comment by n1tranquilla** [comment]
In the [underlying query](https://github.com/Granola-Team/mina-block-explorer/blob/main/graphql/queries/stakes.graphql#L14) for this page, we are using the `countDelegates` property. Unfortunately, the keys of the delegators are no exposed. I don't think we can get at this data readily, which makes me think this falls under `maintenance` category.

**Comment by trevorbernard** [comment]
Querying for all the delegates for a particular account is straight forward but doing it for every account is untenable with our current indices.

```graphql
query StakesDelegators {
  stakes(query: {epoch: 42, delegate: "B62qpge4uMq4Vv5Rvc8Gw9qSquUYd6xoW1pz7HQkMSHm6h1o7pvLPAN"}, limit: 10000) {
    balance
    delegate
    nonce
  }
}
```

**Comment by n1tranquilla** [comment]
I will have to do some thinking about how we should reveal this information to the user. It might require a new page, or it might require some deep linking to the same page.

**Comment by n1tranquilla** [comment]
One solution is to add a delegations to the account overview page. There already exists 3 subsections to this page
* User commands
* SNARK Work
* Block Production

We could add a 4th: Delegations

Likely this page should be reorganized and the tabs above the spotlight repurposed to show the subsections.

* Repurpose Account Spotlight page tabs
* Add Delegations tab to Account Spotlight

**Comment by n1tranquilla** [comment]
Blocked by
* https://github.com/Granola-Team/mina-block-explorer/issues/948
* https://github.com/Granola-Team/mina-block-explorer/issues/947

Solution will be to link to `Account Spotlight -> Delegations` tab from `Stakes Page -> Delegates` column
