### ISSUE TITLE
Problem: there is no easy way to discover the delegators of a delegate

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-block-explorer#510]
Example in MinaExplorer.com: https://minaexplorer.com/wallet/B62qqjvE7v6Qrf1h7xtn4U57eMq8m7CPpkgwS3aCY8w9jQgnzAoPoUp/delegations

**Comment by n1tranquilla** [comment]
This is marked as `MinaExplorer.com Equivalence` but I don't know of way of getting this data without precomputed views. This makes me think this belongs in the `Maintenance` milestone.

**Comment by robinbb** [comment]
Alas, this is integral to analysis. So, despite the fact that ME does not provide a way to query this, we'll have to create front-end features for the front-end to be considered complete and equivalent to ME.

**Comment by robinbb** [comment]
... so, the options are: create some bogus data to display, or simply wait until MI becomes the back-end.

**Comment by n1tranquilla** [comment]
Based on yesterday's team meeting (internal decision) I think we decided on the latter.

**Comment by n1tranquilla** [comment]
This might be done now that we have columnar search for staking ledger. See this page for example: https://minasearch.com/staking-ledgers?q-delegate=B62qj287L1bwP9XguURbxW5cneTRD8Kde4vx3fbeZCNxNxyMzXdsYLP

**Comment by robinbb** [comment]
What will be displayed for delegates that have 10,000+ delegators? How can one discover the count of delegators for a delegate?

**Comment by n1tranquilla** [comment]
Currently, we cannot. It will be capped at 100 records in that table and you won't have a sense of the total amount of delegators.

So perhaps we do need an additional view. I will keep this ticket open.

**Comment by n1tranquilla** [comment]
Actually, we can get the number of delegators: https://minasearch.com/staking-ledgers?q-key=B62qpge4uMq4Vv5Rvc8Gw9qSquUYd6xoW1pz7HQkMSHm6h1o7pvLPAN.

This is the staking for MinaExplorer.com

**Comment by Isaac-DeFrain** [comment]
Related to #500

**Comment by Isaac-DeFrain** [comment]
Reopened by mistake. Closing
