### ISSUE TITLE
Include metric about block producer health on home page

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-block-explorer#511]
MinaExplorer has a "block producer in 24 hours" metric, which is probably unique block production accounts in last 24h. I propose a better metric: unique block producers in last 1000 blocks.

**Comment by n1tranquilla** [comment]
This is marked as `MinaExplorer.com Equivalence` but I don't know of way of getting this data reasonably without precomputed views. This makes me think this belongs in the `Maintenance` milestone.

This query "works" and is quite slow:
```
query MyQuery {
  blocks(limit: 1000, sortBy: BLOCKHEIGHT_DESC) {
    blockHeight
    canonical
    creator
    dateTime
    receivedTime
    snarkFees
    stateHash
    stateHashField
    txFees
  }
}
```

This metric could be created client-side but seems to fit into analytics, and thus the maintenance contract. @robinbb what do you think?

**Comment by robinbb** [comment]
I think that it can go into Maintenance milestone, indeed.

**Comment by n1tranquilla** [comment]
Blocked by: https://github.com/Granola-Team/mina-block-explorer/issues/782

**Comment by robinbb** [comment]
Moving this to backlog because I don't think Nathan's working on it.

**Comment by n1tranquilla** [comment]
Resuming work on this as #782 is resolved
