### ISSUE TITLE
Problem: no "multi-search box" on home page

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-block-explorer#512]
On the home page (and maybe elsewhere), there shoud be a "multi-search box" that will allow exact searches upon any of:
- block state hash
- transaction hash
- block height
- public key
- username

**Comment by n1tranquilla** [comment]
@robinbb I think we should close this in favour of #465 . Can you confirm? If you agree, please close the ticket.

**Comment by n1tranquilla** [comment]
This will be closed by https://github.com/Granola-Team/mina-block-explorer/pull/522
