### ISSUE TITLE
Integrate the mina-block-search frontend to the indexer

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-block-explorer#537]
Now that we have the majority of the GraphQL endpoints, it's time to integrate with the frontend. 

https://docs.google.com/spreadsheets/d/1dQJZx-k0dc4i5wgB_URrIYqIV_SgIFBK7_fShw8h9tc/edit#gid=0

**Comment by n1tranquilla** [comment]
@trevorbernard this ticket is too broad, IMHO. I think the scope needs to be narrower. If you agree, can you close this ticket and reopen others with a more specific problem?
