### ISSUE TITLE
We aren't using the Indexer's GraphQL endpoint for account spotlight and account listing

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-block-explorer#543]
We currently stub data for the accounts listing.

```
type Account {
  public_key: String,
  username: String,
  balance: String,
  nonce: Int,
  delegate: String,
  time_locked: Boolean
}

type AccountQueryInput {
  public_key: String
}

enum AccountSortByInput {
  BALANCE_DESC
}
```

**Comment by trevorbernard** [comment]
That shouldn't block the development of the feature. Missing is the `time_locked` information in the indexer's ledgers. We expose the best ledger in the accounts GQL API. That should be linked to this issue.

**Comment by trevorbernard** [comment]
Time locked was added here: https://github.com/Granola-Team/mina-indexer/issues/748. This issue is no longer blocked

**Comment by trevorbernard** [comment]
This issue is blocked by: https://github.com/Granola-Team/mina-indexer/issues/876

**Comment by robinbb** [comment]
Blocked on Granola-Team/mina-indexer#915

**Comment by robinbb** [comment]
No longer blocked, I think.
