### ISSUE TITLE
Allow user columnar search inputs to remain focused during data fetches for blocks page

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-block-explorer#568]

**Comment by n1tranquilla** [comment]
It is preferred to keep the focus within the input box after the debounce interval fires. That is the preferred solution.

**Comment by robinbb** [comment]
Arguably, this is a bug, since, without this change, a slow typist cannot enter their desired block height (or whatever they're inputting).

**Comment by n1tranquilla** [comment]
Repurposing this issue to be specific to the /blocks page. We will generate a series of tickets to address the other pages from the solution found in: https://github.com/Granola-Team/mina-block-explorer/pull/576
