### ISSUE TITLE
Update header

### ISSUE THREAD

**Issue by jhult** [Granola-Team/mina-block-explorer#594]
1. Move `Powered by Granola` to footer
2. Make `Granola` link the "link" color (so it is obvious it is a link without hovering)
3. Remove `Mina Blockchain Explorer`
4. Change search placeholder text to: `Paste  ->  Enter  ->  Explore the Mina blockchain`
5. Remove extra padding between search bar and menu

**Comment by robinbb** [comment]
Could be separated into multiple issues.
