### ISSUE TITLE
Problem: SNARK gql queries include workIds

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-block-explorer#595]
Remove the workIds from the frontend SNARK query.

**Comment by jhult** [comment]
Relates to #601

**Comment by n1tranquilla** [comment]
I no longer see any work ids present in these places:
* https://minasearch.com/snarks
* https://minasearch.com/addresses/accounts/B62qr9zQ1LKnKM3d7wmFVjv3TzSV6fnXBZ162scK49NTHCA8Xc7PVKq
