### ISSUE TITLE
Entire footer not visible on mobile

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-block-explorer#609]
<img width="534" alt="Screen Shot 2024-05-10 at 3 14 23 PM" src="https://github.com/Granola-Team/mina-block-explorer/assets/19426804/1a94636b-5667-453a-9cad-795550345c49">

**Comment by jhult** [comment]
Caused by https://github.com/Granola-Team/mina-block-explorer/pull/607

**Comment by jhult** [comment]
@n1tranquilla, thanks for taking over this. I had not yet made time for it.
