### ISSUE TITLE
Entire searchbar placeholder text not visible on mobile

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-block-explorer#610]
<img width="534" alt="Screen Shot 2024-05-10 at 3 14 17 PM" src="https://github.com/Granola-Team/mina-block-explorer/assets/19426804/3006620d-015d-4771-8c98-b9d4f9e1424a">

**Comment by jhult** [comment]
Caused by https://github.com/Granola-Team/mina-block-explorer/pull/607

**Comment by jhult** [comment]
I vote `Explore` so we keep the connotation of a blockchain explorer.
