### ISSUE TITLE
Problem: the (next)stakes ledger pages uses `balance` for the `STAKE` column

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-block-explorer#625]
The total stake for an account can be queried with the following GQL:

```
{
  stakes(query:{epoch: 77}) {
    delegationTotals {
      totalDelegated
    }
  }
}
```

Use total delegated rather than the balance

**Comment by jhult** [comment]
Relates to https://github.com/Granola-Team/mina-indexer/issues/890
