### ISSUE TITLE
We don't have a full list of Berkeley integrations required for stubbed views

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-block-explorer#645]

**Comment by jhult** [comment]
Relates to https://github.com/Granola-Team/mina-indexer/issues/902

**Comment by n1tranquilla** [comment]
## How to view the stubbed pages
To view the stubbed pages locally, add the following to your `.env` file 
```
BERKELEY_FEATURES_ENABLED=true
```
and run `just clean dev`

The additional stubbed views for Berkeley will be apparent.


## Tokens
![Image](https://github.com/Granola-Team/mina-block-explorer/assets/19426804/4bd42f75-5b25-43c6-ae3d-3d4858c60bc9)

`Tokens list` is a addresses page for listing all the tokens. It will require the following columns
* Token Name (searchable)
* Token ID (searchable)
* Supply
* Token Owner
* Token Holders (count)
* Total Transactions (count)
* Locked Status

## ZK Apps
![Image](https://github.com/Granola-Team/mina-block-explorer/assets/19426804/7077bae6-80f4-42f4-9a53-0b32d2e04585)

`ZK Apps` is a page listing zk apps independently of other accounts. It is an address listing page for zk Apps. It will require the following columns
* Account (searchable)
* Balance
* Command (count)
* Delegate

*NOTE*: We will also need to distinguish these pages from the existing accounts. The accounts list must not load tokens or zk apps, as these are presented on separate tabs

## Zk App Commands
![Image](https://github.com/Granola-Team/mina-block-explorer/assets/19426804/436bc00e-d373-4e27-a10d-b7492e1601d5)

`ZK Apps Commands` is page for listing all commands from all zk apps. It requires the following columns:
* Hash
* Prover
* Age
* Updates made within the command (count)
* Updated accounts (pks)
* Any transacted amounts (mina or other token)

## Zk App Spotlight
![Image](https://github.com/Granola-Team/mina-block-explorer/assets/19426804/d30c1684-ebb0-456d-b39f-1801af70b50b)
![Image](https://github.com/Granola-Team/mina-block-explorer/assets/19426804/0b946125-58f4-43b0-a23d-1ad4fc950998)

`Zk App Spotlight` page is for inspecting a zk app transaction (or token transaction). It will require the following information
* Block height
* Fee payer
* Txn Hash
* Block Hash
* Type (zk or not)
* Number of accounts updated within the app command
* Balance change (if any)
* Token ID (if any token was involved)
* App State (json array)
* Permissions of the app (json object)

**Comment by robinbb** [comment]
@Isaac-DeFrain
