### ISSUE TITLE
Problem: The current pagination solution does not let us sufficiently explore the blockchain

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-block-explorer#646]
Solution:
* Remove all pagination controls.
* Querying by height or slot should be a less-than-equal-to query, returning that block and lower blocks, or that slot and lower slots
* Maximum size of any query should be 100 blocks, all displayed on one page.
* Should display one of two messages somewhere in the table (header or footer)
  * Showing 100 of all (if more than 100 rows)
  * Showing 17 of 17 (eg)

**Comment by robinbb** [comment]
"Showing 100 of many" should be something more clear about the fact that *all* of the rows were searched/filtered. So maybe "Showing 100 of all"/"showing all" results. Eventually, "all" to be replaced by actual count.

**Comment by n1tranquilla** [comment]
@robinbb agreed.

**Comment by n1tranquilla** [comment]
Requirements updated.
