### ISSUE TITLE
There is no tabular summary information for epochs

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-block-explorer#653]
We need a page to list summary data for each epoch (tabular)
* epoch number
* ledger hash
* fill rate
* blocks produced

See these for inspiration:
* https://minaexplorer.com/top-epoch-stakers?epoch=78
* https://minaexplorer.com/staking-ledgers
* https://towerstake.com/mina-time-machine/

**Comment by n1tranquilla** [comment]
@trevorbernard can you update the description with other wants?

**Comment by trevorbernard** [comment]
I would like to see the start and end global slots and wall clock time for start and end of the epoch

**Comment by n1tranquilla** [comment]
@trevorbernard I want to confirm that we don't have an endpoint to support this yet, do we? I'm going to assume we don't and put this in the "blocked" column.

**Comment by trevorbernard** [comment]
We have the REST summary endpoint but nothing in GQL.

**Comment by n1tranquilla** [comment]
We added a staker leaderboard in this PR #1029  which corresponds to https://minaexplorer.com/top-epoch-stakers?epoch=78

We still don't have a page listing all epochs and their ledger hash as in https://minaexplorer.com/staking-ledgers but I don't think this is strictly necessary or even needed.

@jhult can you weigh in on whether you think this task is done?

**Comment by n1tranquilla** [comment]
Moving this to backlog, as I no longer is blocked and likely has low priority, while awaiting further weigh in.
