### ISSUE TITLE
There is no production indexer that we can connect to for the account listing page

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-block-explorer#659]
Solution: Expose the indexer, even prematurely, so that accounts listing page may use it 

Blocks: #543

**Comment by jhult** [comment]
Related to:
- https://github.com/Granola-Team/mina-indexer/issues/851
- https://github.com/Granola-Team/mina-indexer/issues/913

**Comment by robinbb** [comment]
Deployed, prematurely: http://mina-indexer.granola.team:8080/graphql
