### ISSUE TITLE
The front-end does not facilitate username search on accounts listing page

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-block-explorer#662]
```
type Account {
  publicKey: String
  username: String
  balance: Int
  nonce: Int
  delegate: String
  timeLocked: Boolean
}

type AccountQueryInput {
  public_key: String
}

enum AccountSortByInput {
  BALANCE_DESC
}
```

**Comment by robinbb** [comment]
Blocked on https://github.com/Granola-Team/mina-indexer/issues/896

**Comment by robinbb** [comment]
@n1tranquilla Is this still blocked?

**Comment by trevorbernard** [comment]
What do you mean by "partial search"? Like prefix matching? Or exact username match?

**Comment by n1tranquilla** [comment]
On the accounts page, I think we should support searching by username. Which means that I might not know the full username, and am expected to get a partial match. Let me see if this belongs in equivalence or not.

**Comment by n1tranquilla** [comment]
This is not supported in minaexplorer.com and so this belongs in "maintenance": https://minaexplorer.com/ledger

**Comment by Isaac-DeFrain** [comment]
No longer blocked

![Image](https://github.com/Granola-Team/mina-block-explorer/assets/42081488/f98a74a0-646b-47d7-8901-28fb5acf3f7d)

**Comment by Isaac-DeFrain** [comment]
Related Granola-Team/mina-indexer#1065 & Granola-Team/mina-indexer#1066
