### ISSUE TITLE
Analytics chart does not render when connected to indexer

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-block-explorer#665]
```
[Tags: @CI] chart renders on page /analytics/commands/internal
```

**Comment by robinbb** [comment]
@n1tranquilla I suggest that you discover what mina-indexer functionality is missing/broken, then create a more precise issue against the mina-indexer repo.

**Comment by n1tranquilla** [comment]
> "Invalid value for argument \"query\", unknown field \"dateTime_gte\" of type \"FeetransferQueryInput\""

**Comment by n1tranquilla** [comment]
Duplicate of https://github.com/Granola-Team/mina-block-explorer/issues/691
