### ISSUE TITLE
Augment summary endpoint with indexed totals

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-block-explorer#668]
blocks indexed 
user commands indexed
internal commands indexed
snark work indexed
total accounts indexed

**Comment by Isaac-DeFrain** [comment]
https://github.com/Granola-Team/mina-indexer/pull/932

**Comment by jhult** [comment]
@Isaac-DeFrain, does https://github.com/Granola-Team/mina-indexer/pull/932 resolve this issue?

**Comment by Isaac-DeFrain** [comment]
Resolved by https://github.com/Granola-Team/mina-indexer/pull/1019
