### ISSUE TITLE
Augment GQL with indexed totals

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-block-explorer#669]
1. blocks
- [x] per account per epoch
- [x] per account total
- [x] per epoch
- [x] total

2. user commands
- [x] per account per epoch
- [x] per account total
- [x] per epoch
- [x] total

3. internal commands
- [x] per account per epoch
- [x] per account total
- [x] per epoch
- [x] total

4. snarks
- [x] per account per epoch
- [x] per account total
- [x] per epoch
- [x] total

**Comment by Isaac-DeFrain** [comment]
Granola-Team/mina-indexer/pull/939

**Comment by Isaac-DeFrain** [comment]
For internal commands, do we want fee transfers _AND_ coinbases

**Comment by Isaac-DeFrain** [comment]
Related Granola-Team/mina-indexer#966

**Comment by Isaac-DeFrain** [comment]
Related Granola-Team/mina-indexer#967

**Comment by Isaac-DeFrain** [comment]
Related Granola-Team/mina-indexer#968

**Comment by robinbb** [comment]
I appreciate the checklist in the description, FYI.

**Comment by Isaac-DeFrain** [comment]
Related Granola-Team/mina-indexer#984
