### ISSUE TITLE
No method named `clipboard` found for struct `Navigator` in the current scope

### ISSUE THREAD

**Issue by jhult** [Granola-Team/mina-block-explorer#671]
<img width="860" alt="image" src="https://github.com/Granola-Team/mina-block-explorer/assets/9849069/229b049f-0418-4e80-b03c-40a3b3503ade">

This doesn't prevent using `just dev`. However, it does prevent `trunk build --release --filehash true` from compiling (at least locally, unsure about CI).

**Comment by robinbb** [comment]
Tricky one.

**Comment by jhult** [comment]
I [initially tried](https://github.com/jhult/mina-block-explorer/commit/28fe71a9ab94aaddc522cd36966f9935b09b5b36) to have `[build]` `target = "wasm32-unknown-unknown"`.

However, that caused issues:
```shell
target/wasm32-unknown-unknown/debug/deps/mina_block_explorer-4dea99a3bc484a0d.wasm: 1: Syntax error: end of file unexpected
```

So, I ended up just always setting `rustflags = ["--cfg=web_sys_unstable_apis"]` in `build`. 

Note that this likely causes issues with incremental compilation [[1](https://github.com/rust-lang/rust-analyzer/issues/12688), [2](https://github.com/emilk/eframe_template/issues/93)].
