### ISSUE TITLE
Age and amount columns have redundant info and can seem crowded

### ISSUE THREAD

**Issue by jhult** [Granola-Team/mina-block-explorer#677]
In the `Age` column, the time zone is always `UTC`. Putting this in the header makes the column feel less cluttered. In addition, you can see how `UTC` is currently being cut off (for my screen resolution).

<img width="1512" alt="image" src="https://github.com/Granola-Team/mina-block-explorer/assets/9849069/9384fa5f-f232-4133-90a8-263857a5ddb6">

Similarly, amount columns (`Coinbase`, `Amount`, `Fee`, etc.) all show the same currency (`MINA`). This could be put in the header instead.

**Comment by robinbb** [comment]
I think there are 2 issues, here.

**Comment by n1tranquilla** [comment]
What is the desired solution? Should we keep only the age?

**Comment by robinbb** [comment]
I merely meant to say that there are 2 separate issues: there is the time/UTC issue, then there is the MINA issue.

Not expressing a desired solution.

The overly-long date-time could be moved to a tooltip? The MINA could be moved to a column header?

**Comment by n1tranquilla** [comment]
We can move the date to a tooltip, np.
