### ISSUE TITLE
Internal Commands: Filtering by height has no effect

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-block-explorer#681]
![2024-05-24 09 30 02](https://github.com/Granola-Team/mina-block-explorer/assets/19426804/5b8d988e-604a-404a-9d9c-3e5c278d0cbd)

**Comment by trevorbernard** [comment]
Resolved by: https://github.com/Granola-Team/mina-indexer/pull/959

**Comment by robinbb** [comment]
This is in the Done column, but not closed. I will close. @n1tranquilla re-open if the issue is not resolved, please.
