### ISSUE TITLE
Analytics: Internal Commands Analytics tab does not render

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-block-explorer#691]
> (uncaught exception)TypeError: Cannot read properties of null (reading 'feetransfers')

<img width="1840" alt="Screen Shot 2024-05-24 at 10 23 25 AM" src="https://github.com/Granola-Team/mina-block-explorer/assets/19426804/e4570459-2dd5-4663-8a08-2ba45b303355">

```
{
    "data": null,
    "errors": [
        {
            "message": "Invalid value for argument \"query\", unknown field \"dateTime_gte\" of type \"FeetransferQueryInput\"",
            "locations": [
                {
                    "line": 2,
                    "column": 22
                }
            ]
        }
    ]
}
```

**Comment by trevorbernard** [comment]
This is blocked by: https://github.com/Granola-Team/mina-indexer/issues/960

**Comment by trevorbernard** [comment]
This issue is no longer blocked if you use blockHeight_gte

**Comment by n1tranquilla** [comment]
Can confirm. We are no longer using date, but `blockHeight_gte`. https://github.com/Granola-Team/mina-indexer/issues/960 can be deprioritized.

**Comment by robinbb** [comment]
Should use global slot instead.
