### ISSUE TITLE
Sorting by Stake Weight is not supported

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-block-explorer#706]
BALANCE_DESC is in query: 
```
{"variables":{"limit":100,"sort_by":"BALANCE_DESC","query":{"epoch":0}},"query":"query StakingLedgersQuery(\n  $limit: Int = 10\n  $sort_by: StakeSortByInput!\n  $query: StakeQueryInput!\n) {\n  stakes(limit: $limit, sortBy: $sort_by, query: $query) {\n    balance\n    chainId\n    delegate\n    epoch\n    ledgerHash\n    nonce\n    pk\n    public_key\n    token\n    voting_for\n    delegationTotals {\n      totalStakePercentage\n      countDelegates\n      totalDelegated\n    }\n  }\n}\n","operationName":"StakingLedgersQuery"}
```

Result: 
<img width="2032" alt="Screen Shot 2024-05-28 at 11 27 02 AM" src="https://github.com/Granola-Team/mina-block-explorer/assets/19426804/0bbcf304-3e2f-4a35-b6cd-0819969183b1">

**Comment by n1tranquilla** [comment]
It would seem the "stake" column is mislabeled:

> I think the STAKE column is mislabeled. This is the balance associated for that PK and not the stake. The stake can be queried like so:
{
  stakes(query:{epoch: 77}) {
    delegationTotals {
      totalDelegated
    }
  }
}

**Comment by n1tranquilla** [comment]
Assigning to @trevorbernard as he has indicated this work might be in progress in some branch.

**Comment by robinbb** [comment]
@trevorbernard api.minasearch.com is not out of date.

**Comment by robinbb** [comment]
@n1tranquilla Please confirm that this is supported in the indexer (now that it is correctly deployed).

**Comment by n1tranquilla** [comment]
This is now supported in the indexer. The implementation of this will be in #501
