### ISSUE TITLE
Problem: integers should be right-aligned in tables

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-block-explorer#737]
Consider the following column of decimal (possibly floating point) numbers:
```
3.141
12
12345.6
9.8765432
```
Above, they are left-aligned. Note that it is difficult to quickly read the magnitudes of the numbers, and the jaggedness of the right hand side. For that reason, type-set books and other documents with considered layout align the decimal numbers on the decimal separator ('.' in English). It should look like this:
```
     3.141
    12
12,345.6
     9.8765432
```

**Comment by robinbb** [comment]
This also implies that columns of integers should be right-aligned.

**Comment by n1tranquilla** [comment]
The integer case is easy, i'll create a separate task for the decimal case.

**Comment by n1tranquilla** [comment]
https://github.com/Granola-Team/mina-block-explorer/issues/921

**Comment by n1tranquilla** [comment]
Repurposing this ticket to deal with the integer case.
