### ISSUE TITLE
Important regression tests have been commented out

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-block-explorer#740]

**Comment by n1tranquilla** [comment]
Blocked on https://github.com/Granola-Team/mina-indexer/issues/1046

**Comment by n1tranquilla** [comment]
Waiting for API to stabilize.

**Comment by robinbb** [comment]
transaction spotlight:

  // it("renders the tooltip for stake delegations", () => {
  //   cy.visit(`/commands/${FIRST_TXN_HASH}`);                  
  //   cy.get("section#spotlight-section table").within(() => {
  //     cy.get("th").contains("Amount").as("amount");
  //     cy.get("@amount").parent("tr").as("row");
  //     cy.get("@row").within(() => {
  //       cy.get("td .tooltip").should(
  //         "have.attr",
  //         "title",
  //         "Stake delegations have no transacted amount",
  //       );
  //     });
  //   });
  // });

single-search-result:

    // TODO: uncomment when https://github.com/Granola-Team/mina-indexer/issues/1069 is fixed
    // {
    //   origin: "/staking-ledgers?epoch=1",
    //   input: DEFAULT_ACCOUNT_PK,
    //   tableHeading: "Staking Ledger",
    //   column: "Key",
    // },

All of user-commands/memo.

**Comment by n1tranquilla** [comment]
Blocked by https://github.com/Granola-Team/mina-block-explorer/issues/801

**Comment by robinbb** [comment]
The tests were commented out in order to help with integration with the back-end, so I'll move this to the appropriate milestone: Integration.

**Comment by robinbb** [comment]
user-command/memo still commented out.

**Comment by n1tranquilla** [comment]
Blocked by https://github.com/Granola-Team/mina-indexer/issues/1106

**Comment by robinbb** [comment]
@n1tranquilla It appears that the blocking issue has closed, so I am moving this to 'Next'.
