### ISSUE TITLE
No good way to explore addresses other than by PK

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-block-explorer#764]
We can filter by public_key but that's the only way to filter through the current ledger

**Comment by n1tranquilla** [comment]
@trevorbernard do we support filtering by username yet?

**Comment by n1tranquilla** [comment]
Blocked by #662

**Comment by robinbb** [comment]
#662 was closed, so moving to backlog.

**Comment by n1tranquilla** [comment]
Blocked on https://github.com/Granola-Team/mina-indexer/issues/1066

**Comment by trevorbernard** [comment]
We have the ability to search by username. Closing
