### ISSUE TITLE
Problem: memo field appears associated with account, suggesting that it is a username

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-block-explorer#765]
See, for example, the Accounts view for CkpZhvEYxb9YFZULWEw61khrHAqGZhTktZSiGQ1CKfe6n2TcnxdgD - the FROM column has the account (PK), and underneath of that, a memo "whisperit...". The latter seems to be a username - why else would it be grouped with the account?

**Comment by n1tranquilla** [comment]
We are going to move the memo under the txn hash field

**Comment by n1tranquilla** [comment]
We discussed having this as a separate column as well. Until this is queryable (indexed), I think we should place all memo fields under the txn hash. When indexed, we can make a separate column.
