### ISSUE TITLE
Problem: block producers metric might not be clear enough

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-block-explorer#806]
"Block Producers in last 1000 Blocks" reading "157" might not make it clear enough that the count of 157 is of *unique* block producers.  Also, does that count include block producers who produced a block that did not end up on the canonical chain?

**Comment by n1tranquilla** [comment]
We are running into space issues. We might get around that by saying

```
157 (unique)
Block Producers (last 1000 blocks)
```
or we could say
```
157
Recent Unique Block Producers
```

Any other ideas?

**Comment by n1tranquilla** [comment]
```
157
Unique Producers of last 1000 Blocks
```
