### ISSUE TITLE
Problem: "Block Height" metric has unclear semantics

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-block-explorer#807]
"Block Height"? The user might think that blocks each have a height, and the current height is 9999, say. It is the chain of blocks that has this height (or length). I think that it must be "Blockchain Height" or "Blockchain Length". The protocol itself uses the term "blockchain length" in its blocks, note. So, that term is the least ambiguous, IMO.

**Comment by robinbb** [comment]
ME has "Blockchain Length" as its metric.

**Comment by Isaac-DeFrain** [comment]
To muddy the waters, the "height" of a node in a tree is the "length" of the chain of nodes from root to the desired node (inclusive) - 1. These two terms are consistently used as synonyms.

**Comment by robinbb** [comment]
Ah, so it *is* the case that each block has a "heigh" property, after all. I feel that this strengthens the argument for a rename of this metric to simply "Blockchain Length".
