### ISSUE TITLE
If staking ledger search (Paste -> Enter -> Explore! menu) fails, we should return the canonical block with that height instead

### ISSUE THREAD

**Issue by Isaac-DeFrain** [Granola-Team/mina-block-explorer#810]

**Comment by robinbb** [comment]
Yes, agreed.

**Comment by n1tranquilla** [comment]
I'm not sure I understand. Did you mean that if we paste `100` and the staking ledger doesn't exist, we should return block `100` instead? Should we go to the spotlight page or the /blocks page?

**Comment by n1tranquilla** [comment]
Let's go with the /blocks view.

**Comment by n1tranquilla** [comment]
![Image](https://github.com/Granola-Team/mina-block-explorer/assets/19426804/bf66afc9-5100-4da4-bffb-353abdcc7811)

**Comment by n1tranquilla** [comment]
Blocked by https://github.com/Granola-Team/mina-indexer/issues/1104
