### ISSUE TITLE
memos are no longer showing up on the user command listing page and user command spotlight

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-block-explorer#824]
Though they are returned decoded the GQL request. The memo should be: `whisperit#8145`

https://minasearch.com/commands/CkpZhvEYxb9YFZULWEw61khrHAqGZhTktZSiGQ1CKfe6n2TcnxdgD?q-state-hash=3NLjanAoyqjqmPsQHafJcvQiGW2xbvyXANHxEyNwPwan2eUoZBV9

**Comment by n1tranquilla** [comment]
Will be closed with https://github.com/Granola-Team/mina-block-explorer/pull/821
