### ISSUE TITLE
Display consistent symbols

### ISSUE THREAD

**Issue by Isaac-DeFrain** [Granola-Team/mina-block-explorer#844]
Total stakes don't have `%` but block win does
![Image](https://github.com/Granola-Team/mina-block-explorer/assets/42081488/595e5794-a39c-4691-810c-927ce9c1052e)

**Comment by n1tranquilla** [comment]
This seems to be resolved



![Image](https://github.com/Granola-Team/mina-block-explorer/assets/19426804/ad6bb1af-8fa0-42f4-9a94-f0337b9d54a5)
