### ISSUE TITLE
Main app content (tables) appear secondary due to height of banner.

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-block-explorer#848]
On my desktop, the tables or main content are visible at the screen midpoint due to the height of the banner. I suggest we reduce the height to make the content more prominent

<img width="2032" alt="Screen Shot 2024-06-14 at 11 17 11 AM" src="https://github.com/Granola-Team/mina-block-explorer/assets/19426804/2dc9f6ee-74e5-40cb-9530-b7ed49b02d6e">

**Comment by robinbb** [comment]
I suppose that the height of the banner depends on how much one wants to emphasize the "under construction" part of the sight. I'm open to options beyond what we now have.
