### ISSUE TITLE
Insufficient randomness on the trunk port in CI

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-block-explorer#862]
Occasionally, two tests will run in parallel in CI originating from two different PRs, but they use the same port for trunk. If one test closes, it will shut down the local trunk server, affecting the outcome of other CI jobs, if they happen to be listening on the same port

**Comment by n1tranquilla** [comment]
We discussed that this may not be necessary since @robinbb will limit the slots available to projects.

@robinbb can you confirm?

**Comment by trevorbernard** [comment]
This has been rock solid for us in the indexer: https://github.com/Granola-Team/mina-indexer/blob/main/tests/regression#L83

**Comment by robinbb** [comment]
I have limited the "concurrency" of the testing, making port conflicts much less likely.

Trevor, FYI, there has still been at least once instance of port conflict, and probably more. Unfortunately, on the mina-indexer test suite, it is possible for one set of tests to incorrectly test the Indexer associated with another set of tests, thereby getting "wrong answers" on its own set without failing. In other words, under certain circumstances, there can be a port conflict and it will not be detected.
