### ISSUE TITLE
Add prepush hook to run tier1 tests

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-block-explorer#864]

**Comment by n1tranquilla** [comment]
This was added to prevent unnecessary alarm for failing CI tests. I think we discussed that this might not be needed so long as we keep a project in "Draft" until CI passes.

@robinbb to confirm.

**Comment by robinbb** [comment]
One cannot ensure that devs run any hook, so I'm okay not to include any change in the repo.
