### ISSUE TITLE
Display applied/failed for each transaction

### ISSUE THREAD

**Issue by Isaac-DeFrain** [Granola-Team/mina-block-explorer#874]
These txns are all failed
![Image](https://github.com/Granola-Team/mina-block-explorer/assets/42081488/9516f6cb-f7dd-4049-9c58-ac80ed39b3ec)

**Comment by n1tranquilla** [comment]
Is the block non-canonical?

**Comment by n1tranquilla** [comment]
Minaexplorer does not have this feature (https://minaexplorer.com/block/3NKaS7xcUNwKwopA363syvxLMrLfWcfdXPoHAVJ5wrV8Ss9ZqGYZ), so I'll move to the maintenance milestone

**Comment by robinbb** [comment]
Consider making it 3 options: canonical, non-canonical (failed), or pending.

**Comment by Isaac-DeFrain** [comment]
Whether a txn is "applied" or "failed" is independent of canonicity

**Comment by robinbb** [comment]
Oh, I misunderstood what you were asking for. Thanks for explaining. Ignore my comment about canonicity.

**Comment by robinbb** [comment]
It seems we need a new column to indicate "success"?

**Comment by robinbb** [comment]
... and maybe some increased opacity or some other way to visually indicate failed transactions.

**Comment by n1tranquilla** [comment]
I think we need a green dot or a red dot, like the other pages. That or we include block canonicity on each tab

**Comment by n1tranquilla** [comment]
Here is an example: https://minasearch.com/blocks/3NKR3LoD3TLQ4Gotmhg59xUYcuq9hwVMuEujT99QywJhkDTYWwDy/commands/user

**Comment by robinbb** [comment]
I don't think this is done. Example: https://minasearch.com/commands/CkpZQZKNTBYRHGVHezJ9QSymSDBovmjSqhbcCAWWUFPNqB3ih7T9K there is no evidence that this is not applied.
