### ISSUE TITLE
Unapplied transactions are not distinguished from applied txns

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-block-explorer#885]
https://minasearch.com/commands/user?q-txn-hash=CkpYttS5Dn3LLhqsknekxUQZCaB6W3jMiaQRiQFZMaWgMf6hdzk31

**Comment by jhult** [comment]
Relates to https://github.com/Granola-Team/mina-block-explorer/issues/874

**Comment by n1tranquilla** [comment]
Duplicate of https://github.com/Granola-Team/mina-block-explorer/issues/874

**Comment by n1tranquilla** [comment]
Not a dup
