### ISSUE TITLE
Problem: UI has extraneous zeroes at the end of nearly every numeric value

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-block-explorer#888]

**Comment by n1tranquilla** [comment]
This may be desired if accuracy down the nanomina is desired.

**Comment by robinbb** [comment]
But "0.01" is how "0.010000000" should be displayed. It's the unnecessary zeroes that is unconventional and difficult to read.

**Comment by robinbb** [comment]
Nathan's comment reveals that this is not a bug.
