### ISSUE TITLE
Excessive memory consumption over time

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-block-explorer#896]
<img width="2032" alt="Screen Shot 2024-06-23 at 7 44 38 AM" src="https://github.com/Granola-Team/mina-block-explorer/assets/19426804/defe5309-149c-4e14-a108-58346a9cb3b5">

Likely this is due to excessive `.clone()` + polling causing memory to slowly grow over time. The same is observed when doing many interactions in a short period of time (cypress headed testing)

**Comment by n1tranquilla** [comment]
Able to reproduce locally by running the same test repeatedly. Memory consumption increases over time.

**Comment by n1tranquilla** [comment]
@robinbb has your tab been crashing?

**Comment by robinbb** [comment]
@n1tranquilla Not recently, but I haven't kept it open for long.

**Comment by n1tranquilla** [comment]
Try keeping the tab open as I don't think it's a problem any longer. I haven't seen memory usage spike.

**Comment by robinbb** [comment]
Closing this. Memory consumption tends to stay below that of my email reader. So, good enough.
