### ISSUE TITLE
`Status` column for user commands ought to be filterable by applied/failed status

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-block-explorer#897]

**Comment by n1tranquilla** [comment]
Blocked by https://github.com/Granola-Team/mina-indexer/issues/1207

**Comment by n1tranquilla** [comment]
![Image](https://github.com/Granola-Team/mina-block-explorer/assets/19426804/d44115fe-909d-44ca-8557-6c239a447050)

**Comment by robinbb** [comment]
How would one find non-canonical user commands, then?

**Comment by n1tranquilla** [comment]
Yes, that's a good question, and I would be interested to know if non-canonical means "failed" commands. If that's the case, I think we're not interested in non-canonical user commands, as they are only "failed" and can be found by applying the "failed" filter

**Comment by robinbb** [comment]
My understanding (not certain) is that applied/failed status applies to the transactions and is independent of canonicity, which is a block-level status that applies to the transactions within a given block. So, there are 4 permutations.

**Comment by n1tranquilla** [comment]
Repurposing this issue.

**Comment by n1tranquilla** [comment]
Still locked by https://github.com/Granola-Team/mina-indexer/issues/1207 after repuposing story
