### ISSUE TITLE
The UI displays `?` for total staking records

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-block-explorer#911]

**Comment by n1tranquilla** [comment]
Depends on Granola-Team/mina-indexer#1195

**Comment by n1tranquilla** [comment]
Still blocked on: https://github.com/Granola-Team/mina-indexer/issues/1195

**Comment by robinbb** [comment]
No longer blocked. However, 'prod' does not have this feature, yet.

**Comment by n1tranquilla** [comment]
This issue is in PR and is now blocked by https://github.com/Granola-Team/mina-indexer/issues/1232
