### ISSUE TITLE
Populate unique block producers in last 1000 blocks

### ISSUE THREAD

**Issue by Isaac-DeFrain** [Granola-Team/mina-block-explorer#930]
![Image](https://github.com/Granola-Team/mina-block-explorer/assets/42081488/2353e74e-8075-4fcf-ab26-c52930a14d34)

**Comment by robinbb** [comment]
Could be a different stat, but need to address this soon.

**Comment by n1tranquilla** [comment]
This is probably no longer a very expensive call. I can try enabling it. How soon is "soon" @robinbb ?

**Comment by robinbb** [comment]
@n1tranquilla I would consider this "too expensive" unless it is being pre-calculated by the back-end and ready to serve with any calculation being done. This is because the home page needs to be very responsive. "Soon" is "with top priority", but not "return from vacation to do this".

**Comment by trevorbernard** [comment]
Let's finalize what this stat "should be". Active block producers (validators) over the last 1000 blocks is pretty arbitrary. Looking at the homepage, all the other components represent an important aggregate from the blockchain.

IMHO, what would be better is to display the total number of accounts so it follows with the current theme.

**Comment by robinbb** [comment]
The stat should tell a useful story about how many distinct block producers are cooperating to sustain the chain "recently".

**Comment by Isaac-DeFrain** [comment]
I think we should have this stat and others like it. I agree with @trevorbernard's comment about displaying a more "fitting" stat there

**Comment by Isaac-DeFrain** [comment]
Mayne it makes sense to have a few more "recent" stats and make another row?

**Comment by robinbb** [comment]
Okay, but this issue is urgent because we noticeably have a missing stat in the home page right now.

**Comment by n1tranquilla** [comment]
Blocked by https://github.com/Granola-Team/mina-indexer/issues/1321

**Comment by n1tranquilla** [comment]
Assigning to myself since this is the front-end counterpart to https://github.com/Granola-Team/mina-indexer/issues/1321

**Comment by n1tranquilla** [comment]
Version of indexer deployed does not contain latest change from blocking issue.
