### ISSUE TITLE
Remove account activity dialog

### ISSUE THREAD

**Issue by Isaac-DeFrain** [Granola-Team/mina-block-explorer#931]
![Image](https://github.com/Granola-Team/mina-block-explorer/assets/42081488/e5043aa4-a74b-43f6-89e3-ae72e733930d)

![Image](https://github.com/Granola-Team/mina-block-explorer/assets/42081488/846822de-e813-459b-9de2-0e77cc82672a)

![Image](https://github.com/Granola-Team/mina-block-explorer/assets/42081488/c790431f-c19c-4faf-abff-cc21d18f7b08)

**Comment by n1tranquilla** [comment]
@Isaac-DeFrain does this mean you use this dialog? I was thinking we should remove this dialog as I never use it, and neither does @trevorbernard , according to his feedback last week.

**Comment by robinbb** [comment]
@n1tranquilla removing the dialog will resolve this issue.

**Comment by n1tranquilla** [comment]
Probably we will remove the dialog, it's not necessary.

**Comment by jhult** [comment]
Closing as this is done.
