### ISSUE TITLE
Problem: outstanding API calls accumulated seemingly without bound

### ISSUE THREAD

**Issue by jhult** [Granola-Team/mina-block-explorer#933]
<img width="1391" alt="image" src="https://github.com/Granola-Team/mina-block-explorer/assets/9849069/4c0c3250-b91c-4f09-b69b-2d5ac40cbc90">

**Comment by n1tranquilla** [comment]
Is this a workaround for something broken?

**Comment by n1tranquilla** [comment]
The issue title describes a solution. An alternative title might say "Repeated API calls return 500" or some other symptom. I can't tell the error code from the screenshot, but if we update the title to include the symptom, we might better be able to address the root problem.

**Comment by robinbb** [comment]
I will correct the title.

**Comment by robinbb** [comment]
API calls occur regularly without regard for whether the prior API call has returned. No timeout handling occurs. Even if a prior API call were to return, results would then be pending on a subsequent API call which has not yet returned. Server becomes loaded with API calls that are not even used.

**Comment by n1tranquilla** [comment]
I see. I tried reproducing this the other day and couldn't. Could you add some details on what page/where the problem manifest? The code for polling is located in multiple places and I'm not sure the solution is trivial enough to fix them all.

**Comment by n1tranquilla** [comment]
Ok a closer look at the image provided shows that some calls are taking several minutes. Thanks for the elaboration.

**Comment by n1tranquilla** [comment]
I'm not sure what the solution is for this issue. It seems like we need a workaround until API endpoints are more performant. Should we disable polling until this is not an issue?

**Comment by robinbb** [comment]
Just check to make sure that the prior call has returned before invoking another.

**Comment by n1tranquilla** [comment]
I don't think this is an pressing issue right. It is going to the bottom of the backlog.
