### ISSUE TITLE
Account Spotlight page lacks `updated block #` information

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-block-explorer#934]
Currently, the Account Spotlight page does not provide any indication of the block height up to which the account data is accurate.

**Comment by n1tranquilla** [comment]
Do you mean, we should display on the spotlight page, the highest block number for which there is a transaction with this accounts address?

**Comment by trevorbernard** [comment]
> Do you mean, we should display on the spotlight page, the highest block number for which there is a transaction with this accounts address?

No, the account spotlight references accounts in the current best ledger. This ledger is a snapshot in time, typically referenced as: "The ledger at block height 359604."

**Comment by n1tranquilla** [comment]
Perhaps this is a usage pattern i'm not understanding. I'm guessing that a user (such as yourselves) might want to visit an account page and know what `block height #` we are at without having to navigate to another page to verify. Is this the case? If so, should we put the block height in the footer or somewhere else globally visible?
