### ISSUE TITLE
Account spotlight page lacks account creation fee indicator

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-block-explorer#936]
The account spotlight page currently does not display whether an account incurred an account creation fee. Genesis ledger accounts are not subject to this fee, but every other account is.

**Comment by trevorbernard** [comment]
This issue is blocked by: https://github.com/Granola-Team/mina-indexer/issues/1305

**Comment by n1tranquilla** [comment]
Updated status to "Blocked" due to this comment: https://github.com/Granola-Team/mina-block-explorer/issues/936#issuecomment-2233214594

**Comment by trevorbernard** [comment]
Unblocked: https://github.com/Granola-Team/mina-indexer/pull/1323

**Comment by n1tranquilla** [comment]
This remains blocked as change is not deployed.
