### ISSUE TITLE
Research what is required for SNARKs analytics page

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-block-explorer#987]
Equivalent view: https://minaexplorer.com/analytics/snarks

**Comment by jhult** [comment]
Related #983 has been implemented.

**Comment by n1tranquilla** [comment]
### SNARKs per day in last x blocks:

Can be accomplished by aggregating on the front end
```
query Snarks($limit: Int = 10, $sort_by: SnarkSortByInput!, $query: SnarkQueryInput!) {
  snarks(limit: $limit, sortBy: $sort_by, query: $query ) {
    dateTime
    block {
      stateHash
    }
  }
}

{
  "limit": 10000,
  "sort_by": "BLOCKHEIGHT_DESC",
  "query": {
    "canonical": true
  }
}
```

### Average Snarks per day in last x blocks

Can be accomplished by aggregating on the front end
```
query Snarks($limit: Int = 10, $sort_by: SnarkSortByInput!, $query: SnarkQueryInput!) {
  snarks(limit: $limit, sortBy: $sort_by, query: $query ) {
    dateTime
    fee
    block {
      stateHash
    }
  }
}

{
  "limit": 10000,
  "sort_by": "BLOCKHEIGHT_DESC",
  "query": {
    "canonical": true
  }
}
```

### SNARKS by fee 
already covered by the current table we have here https://minasearch.com/analytics/snarks?limit=5000

### Top snark producers

Covered by snark leaderboard #984 

### Most expensive snark work

Covered by snark leaderboard with an additional sort parameter #984 (new sort parameter is by most expensive snark work)

### total snark fees earned

Covered by snark leaderboard #984 and is the default sort parameter

**Comment by n1tranquilla** [comment]
Issues created 
* #991 
* #992
